### ISSUE TITLE
Seeking tests vectors

### ISSUE THREAD

**Issue by ethicnology** [nostr-protocol/nips#124]
Is there any repository with some test vectors available ?

**Comment by gkbrk** [comment]
BIP340 has some test vectors you can use to check your implementation.

https://raw.githubusercontent.com/bitcoin/bips/master/bip-0340/test-vectors.csv

secp256k1 should also have plenty of test vectors, as it's very popular due to Bitcoin.

Usually to verify things you can just sample some events from relays, not everything will be valid, but a lot of it will be.

**Comment by RandyMcMillan** [comment]
https://github.com/nostr-protocol/nips/pull/138

**Comment by RandyMcMillan** [comment]
You can use nostril to test against...

https://github.com/jb55/nostril/pull/19
