### ISSUE TITLE
Private list for store Gift Wrap keys(NIP-59)

### ISSUE THREAD

**Issue by Anderson-Juhasc** [nostr-protocol/nips#1564]
When we wrap the seal it generate a random private key and if we don't store it we can't edit or delete the message if it is needed.

I propose to create a private list(like private bookmark) to store these keys for later use(edit or delete).

Let me know if it could be a good idea.

**Comment by staab** [comment]
#875 has a "key share" event in which keys are sent to the user for group access. This has the advantage of never accidentally deleting keys due to a race condition, but also doesn't allow for key deletion.

In any case, I don't really think this is a good idea. MLS will hopefully allow better key management for messaging, and in the meantime too many gift wraps are sent to keep track of all sender keys (assuming a different key is used for each wrap).

**Comment by vitorpamplona** [comment]
> if we don't store it we can't edit or delete the message if it is needed.

1. The sender should not be able to delete any message. Only the p-tagged user should be able to delete. 
2. There is no edits/replaceables on 1059 wraps. 

For DMs, you should send a message to yourself. Siince it's your inbox relay, it should allow you to delete anything, like events where you are p-tagged but not the author.

**Comment by Anderson-Juhasc** [comment]
@vitorpamplona I tried to delete the wraps in code and in app, but when I reload the delete don't have effect...

My event:
```javascript
      const deleteEvent = {
        kind: 5,
        pubkey: pubKey,
        created_at: Math.floor(Date.now() / 1000),
        tags: [['e', wrappedGift.id]], // Tag the ID of the event to delete
        content: 'Deleting this direct message.',
      }
      const signedEvent = finalizeEvent(deleteEvent, prvKey)
```

**Comment by vitorpamplona** [comment]
It depends on the relay. Many relays don't delete wraps with p-tags yet.
