### ISSUE TITLE
why is NIP-86 not using RESTful API

### ISSUE THREAD

**Issue by mleku** [nostr-protocol/nips#1616]
i don't see anything in this

https://github.com/nostr-protocol/nips/blob/master/86.md

that requires a server to initiate sending data to the client that isn't requested... it all fits perfectly well into a HTTP based API with HTTP style path/and/query style, eg

`admin.mleku.realy.lol/export/PUBKEYHERE`
`admin.mleku.realy.lol/ban/PUBKEYHERE`

we already have SSH for monitoring log outputs and capturing metrics and all that jazz, so it makes zero sense to use a socket API for something that can be done with authenticated HTTP

**Comment by fiatjaf** [comment]
It is using authenticated HTTP. just not weird REST paths.

**Comment by mleku** [comment]
"weird" when for all the calls that have no parameters you could use curl? 

what's weird about

    http://realy.lol/ban/npub1doodeedooo

it's overly complex???

also regarding auth, you can shift auth control to another layer of the cake such as a wireguard socket, this is much simpler to maintain and i'd argue more secure since you aren't using a well known to be kinda shitty auth system that doesn't use ECDH

it's simple enough to wrap auth into a CURL call but forcing the user to use JSON to wrap an npub seems kinda unnecessary complexity

**Comment by mleku** [comment]
ok, i can understand why this might be a silly thought, as i built in a simple http interface for this purpose in realy that is unauthenticated, assumes a network layer auth such as a wireguard ECDH based channel encryption

a website could have a link that accesses that and funnels it into a javascript that forwards the data out to their network and takes control of your relay

so, it does need an auth protocol really, still, that could be your standard HTTP methods, they are secure enough

anyway, closing the issue, i have to think about my admin port access control now because of this issue

**Comment by fiatjaf** [comment]
> what's weird about
> 
> ```
> http://realy.lol/ban/npub1doodeedooo
> ```
> 
> it's overly complex???

My main argument against it is the same you have for it: I prefer the other way.

But I actually have a more reasonable argument: handling a bunch of different paths with arguments as part of the paths is harder to implement and more error-prone, and may limit some of the arguments.

It's also harder to implement when you have other stuff listening on the relay or on Khatru, for example, where you would have to use a custom router instead of the default Go http router that you may love yourself since you love all the Go things. The Blossom Khatru implementation, for example, is kind of a disaster because of that and backwards-compatibility.

> also regarding auth, you can shift auth control to another layer of the cake such as a wireguard socket

You still can. You can just make your relay not check for any auth. This is supported on Khatru today. But it's good to have the possibility of requiring auth on the open internet.

> standard HTTP methods

You mean POST, PUT, PATCH, HEAD or what? This NIP uses the `Authorization` header, doesn't it? All these HTTP things are made for webpages, not for APIs, it's ok and probably even better to ignore most of them, it's so annoying, so many confusing ways of doing the same thing.
