### ISSUE TITLE
NIP-42 – 1) add challenge to NOTICE/OK 2) keep challenge stable 3) Allow easy account switch

### ISSUE THREAD

**Issue by arthurfranca** [nostr-protocol/nips#172]
@fiatjaf I just thought about this so wasn't fast enough to comment on PR before the merge.

1. I propose this change:
from: `["NOTICE", "restricted: we can't serve DMs to unauthenticated users, does your client implement NIP-42?"]`
to: `["NOTICE", "challenge: theChallengeString. we can't serve DMs to unauthenticated users, does your client implement NIP-42?"]` (or "restricted: theChallengeString. we can't serv...")
`The challenge string MUST NOT contain the "." (dot) char` <- Used to separate the challenge from the optional info message.

This way, the client flow would be much easier, as it will already know the challenge, without an extra round-trip.

2. Also, this change:
`Relay MUST reuse the same challenge for the connection lifetime.`

This is to avoid receiving a challegeX from relay initiated AUTH command and another different challenge from the notice/ok message. Also, it would unlock the below feature easily.

3. Considering the challenge _won't change during the same connection_ (number 2 above), client won't need to ask for it for switching account:
`Client MAY re-authenticate with another pubkey by sending a new AUTH command with the event signed by its corresponding private key.` <- An easier version of what @Semisol  proposed

**Comment by fiatjaf** [comment]
I don't think this helps. The client should already have the challenge at this point. Or, if the relay hasn't sent the challenge yet, it can send the challenge in its own event, no need to mix it in the `NOTICE`.

**Comment by arthurfranca** [comment]
It is possible that the client don't have the challenge already because the relay may not send it on connection if it wishes to just react on some client actions that need authentication.

So currently the relay will send two commands in response to one client action in need of authentication, the `NOTICE` and also the `AUTH` command.
The re-authentication part will be a disconnect > reconnect then all the AUTH and/or NOTICE+AUTH from relay and AUTH from client dance instead of just one AUTH command from the client.

**Comment by fiatjaf** [comment]
> It is possible that the client don't have the challenge already because the relay may not send it on connection if it wishes to just react on some client actions that need authentication.

In this case the relay can send an `AUTH` message with the challenge right before sending the `NOTICE`.

**Comment by barkyq** [comment]
My 2 cents:

 I like 2. and 3. and they are consistent with the implementation at:
https://github.com/fiatjaf/relayer/blob/38d0f481c138e6689e249394b7d75d2e74105662/handlers.go

For 1., I prefer keeping the challenge in AUTH messages (otherwise the client will have to parse the NOTICE, rather than just receive a new AUTH message it is probably already set up to receive and parse). In any case, the client should be set up to receive the challenge message when the relay sends it, and not need to get repeated challenges. In the above implementation, the relay sends AUTH once the websocket is opened.

**Comment by barkyq** [comment]
This NIP says the client may send the `AUTH` on connection start. However, clearly the client cannot send the `AUTH` until the relay sends the challenge, and the NIP says the relay may wait until it whenever it wants to send the AUTH frame?

I think the nip should be more prescriptive on client/relay protocol flow. 

Consider:

Client connects to Relay, wanting to publish an event. But the client is NIP-42 compliant and therefore waits for AUTH challenge before sending the event. However, the AUTH challenge never comes, since Relay B does not implement NIP-42.

Option 1: Client has a timeout, waiting for AUTH challenge, and then proceeds to publish. Will work with most reasonable implementations which send the AUTH challenge right away. But what should the timeout be? Timeouts will be annoying for CLI apps which establish a short-lived websocket connection for the purposes of sending a one-off event.

Option 2: Client assumes Relay does not implement the NIP-42 and publish the event without trying to AUTH. Then, if the relay does require NIP-42, client receives a notice (and hopefully the AUTH challenge) in response. Then the client responds to the challenge and publishes the original event a second time.

I think the NIP could be improved by saying: if the relay implements NIP-42, the challenge SHOULD be sent at the start of the connection.

**Comment by barkyq** [comment]
in an ideal world, there would be a clean and quick way for the client to initiate the authentication and/or determine whether the relay implements authentication.

By using the same TCP connection, one can imagine a scenario similar to NIP-11, where the Client makes some GET request for the AUTH challenge before initiating the websocket handshake. Although as I type this I realize how overkill it sounds. But still I think there is some awkwardness with protocol flow currently with this NIP.

**Comment by fiatjaf** [comment]
Let's wait until this becomes a problem. I think it won't.
