### ISSUE TITLE
NIP for marketplace useful?

### ISSUE THREAD

**Issue by earonesty** [nostr-protocol/nips#322]
Proposal:

Standardized item-for-sale listing format, bid/offers and acceptance messages.

Messages needed:

 - public listing
 - private bid (encrypted to seller's pubk)
 - public bid
 - public acceptance with quantity so engines can decrement/close listing
    - can be used to retract a listing
 - standard for "zaps to pay on acceptance"

Notice the only things that you need is a title, description, a bid with no information, and an acceptance.   No price, location or anything else is technically needed.   For public listings to work, all that can happen in DM's.   The only thing that needs to work is "list and delist".  Other optional information (specifically shipping), is there to allow for better UX around pricing.

Example listing:

```
{
	"title": "title of item for sale",
	"description": "description of item",
	"price": <price in sats>,  # optional
	"shipping": [  # optional
		{
			"country": ["uk", "fr"],
			"service": "overnight",
			"cost": <price in sats>,
		},
		{
			"country": ["us"],
			"region": ["ny", "nj"],
			"service": "4 day air",
			"cost": <price in sats>,
		},
		{
			"country": ["us"],
			"service": "4 day air",
			"cost": <price in sats>,
		}
	],
	"quantity": <quantity available>,   # optional
	"tags": [["l", "digital camera"], ["u", "UPC329498578"]]   # optional
}
```

Bids can be sent via NIP-04 encrypted message to seller, or as a public bid.

```
{
    "content": <optional bid amount + optional region for shipping>
	"tags": [["e", <event-id-for-bid>]]
}
```

**Comment by staab** [comment]
I want marketplaces too, but I think they may be impossible to implement purely on nostr. Listing status must be consistent, otherwise:

- Clients that haven't received the `delist` or `accept` events on a listing will still show sold listings to users (suboptimal UX)
- Sellers could accept multiple bids simultaneously and publish to different relays to double-sell the item

This proposal also doesn't account for escrow, which has the same requirements for locking/unlocking as the above.

Marketplaces might actually be a place where a blockchain would actually be the correct approach, since you need global consistency. Maybe something along the line of zaps could be used to solve that problem. In other words, you could associate the listing with a lightning invoice, then when the invoice is paid the wallet provider publishes a signed event similar to `9735` to acts as a claim for the seller's goods. Again, no escrow, but maybe there's something there.

Related: https://github.com/nostr-protocol/nips/issues/273

**Comment by earonesty** [comment]
ok,

blockchain checkpoint can be used which is the hash of whole current state 

any event author can designate a  bitcoin address as a checkpoint author

any number of sellers can designate  a single checkpoint author, author publishes acceptance with an npub list 

checkpoint author builds a set of current state (all event ids) and publishes the "hash and eventid of sync state" on chain

readers can check the blockchain and be sure that they have the latest state by finding the sync state event which contains the full event id list, needed to match the state hash



readers can

can be used for any notes

**Comment by arcbtc** [comment]
Nostr is partly based on Diagon Alley. Now that's being built on Nostr. Check out the progress here. Should be ready soon. 
https://github.com/lnbits/nostrmarket

**Comment by arcbtc** [comment]
Talk of using blockchains is dumb

**Comment by earonesty** [comment]
I agree it's dumb, i usually leap to solving problems that aren't problems

 - Clients that haven't received the delist or accept events on a listing will still show sold listings to users 
 - Sellers could accept multiple bids simultaneously and publish to different relays to double-sell the item
 
 Answer to both of those is "so what?", now the seller is just another scammer, and there are better ways of dealing with scammers, and certainly a marketplace isn't one of them.

**Comment by earonesty** [comment]
closed because nip15
