### ISSUE TITLE
Relative time offset queries

### ISSUE THREAD

**Issue by blahbleepew** [nostr-protocol/nips#325]
Filters should be allowed to be queried by datetime offsets. i.e. "send me all events you received since 5 minutes ago". Filtering by created_at isn't useful when trying to catch up to a relay because of timezone differences and because clients can spoof timestamps.

Example (tentative):

```json
{
    "kinds": [0, 1, 2],
    "since_offset": 550 // in secs
}
```

**Comment by shafemtol** [comment]
There are no timezone differences. All timestamps are in seconds since 1970-01-01 00:00:00 UTC.

If you want to receive all events as they come in regardless of timestamp, you can leave out any timestamp filter and instead use `limit`. You can combine that with a one-time request for events with a minimum timestamp of e.g. `now - 300` to get all events supposedly created in the last 5 minutes.

With such a filter, if you're not continuously connected to the relay, you do risk missing events that come in with an old timestamp while you are disconnected. This can happen if there are delays in synchronization or someone decides to upload old events to a new relay, perhaps to migrate from another relay. In that case, it would be useful to have some kind of filter that could match recently received events, regardless of their `created_at` value. The name should reflect that it is on received time, not the `created_at` time, e.g.  `received_since`. I would still use absolute time. That works as long as your clock isn't wildly out of sync. The server usually gives you its own time in the HTTP `Date` header in the WebSocket connection itself if you're worried about clock differences.

A different and more robust approach to the same problem might be efficient set reconciliation such as [Minisketch](https://github.com/sipa/minisketch) (I believe @fiatjaf was looking at this and maybe has some ideas?)

**Comment by shafemtol** [comment]
This issue has been brought up earlier: #78 #79

Minisketch was briefly mentioned in #79 as well.

**Comment by blahbleepew** [comment]
> There are no timezone differences. All timestamps are in seconds since 1970-01-01 00:00:00 UTC.

Timezones are whatever the clients send to the relay because there is no way to enforce that. In practice when I do `now - 300` I get floored by events.
