### ISSUE TITLE
Enhance Nip-05 Domain Identifiers. 

### ISSUE THREAD

**Issue by satoshipuzzles** [nostr-protocol/nips#327]
Make Nip-05 Domain Identifiers easier by implementing a tool that enables the protocol to read Cname records in DNS settings.

**Comment by fiatjaf** [comment]
This has been discussed many times.

**Comment by satoshipuzzles** [comment]
I saw that after I posted I apologize for the duplicatity. Nevertheless the verdict seems to still be undecided. I'm just starting to go down the open source rabbit hole and code in general. I was in a nest this morning and someone encouraged me (won't name names) to post this as my first NIP. As you can see on my profile I'm a complete newbie. I just joined Github today for the first time ever! Managing domain identifiers in DNS will dramatically lower the barrier for no code dudes like myself. It will also pave the way for a Nostr email client (not sure if they already exist pardon my ignorance). It seem like an easy win.

**Comment by mikedilger** [comment]
Welcome to github @satoshipuzzles. Since you weren't part of the prior discussions you might want to search for them. The idea has some merit but we already have one way to do it that works well for all clients, and this DNS way won't work for JavaScript clients. And furthermore, nip05 isn't really that great of a thing in the first place.

But nobody controls nostr so you are free to do whatever you want, but other clients/relays probably wouldn't follow. So you'd end up writing your CNAME record and nobody would read it.

**Comment by satoshipuzzles** [comment]
Thanks for the warm greetings Mike! I'm reading up on what I can find now. I just thought it would be really cool if everyone could use their own domains as a cool vanity handle and or a low form of verification. From an outsider's perspective I see it as a way to consolidate your npub, email, lightning address and website all in one easy to remember domain name/ email. Also it makes owning and collecting domains cool again! If someone were to spin up a client and a paid relay that could read CNAME records I think there would be a lot of interest. I'm envisioning a more formal / professional b2b client like linkedin. Could even name it Linkedstr! Anywho I'll stop my rambling now, thanks again for pointing me in the right direction.
