### ISSUE TITLE
Using WebFinger as NIP-05 (fallback)

### ISSUE THREAD

**Issue by pfefferle** [nostr-protocol/nips#482]
NIP-05 seems to be so similar to [WebFinger](https://webfinger.net/), that I would propose to add WebFinger as replacement/at least as alternative to the current NIP-05.

WebFinger is already widly spread and used by Diaspora, OStatus and oder Fediverse plattforms, so it is easier to adopt and helps with interoperability between the different approaches.

Proposal:

URI:

`https://<domain>/.well-known/webfinger?resource=acct:<local-part>@<domain>`

JRD:

```JSON
{
    "subject": "acct:<local-part>@<domain>",
    "properties": {
        "nip05" : "b0635d6a9851d3aed0cd6c495b282167acf761729078d975fc341b22650b07b9"
    }
}
```

**Comment by fiatjaf** [comment]
I don't see how it is easier to adopt, it is just a different JSON structure. Not better nor worse.

Adding this to the NIP-05 spec would just be creating a new format that now _all_ implementations would have to check for, extra work on all clients for zero benefit.

NIP-05 could have used webfinger in the first place, but I've decided to not do it since there would be exactly zero benefits, as servers would still have to implement a new schema specific to Nostr anyway, so why not do something that is simpler and less confusing (because when people read "webfinger" they think it's yet another thing they have to learn in order to implement something, so they give up).
