### ISSUE TITLE
Issue in the `d` tag value for parameterized replaceable events 

### ISSUE THREAD

**Issue by mostafa-khaldi** [nostr-protocol/nips#555]
The replaceable events with the `d` tag that hold a value in a URL format are unfetchable, you get `null` when querying tho the event does exist.

A proposition is to keep the `d` a unique value generated using famous packages such as `nanoid` or `uuid`  .

**Comment by fiatjaf** [comment]
On what relay?

**Comment by mostafa-khaldi** [comment]
Pretty much any relay, I have tested this in the following:
 wss://nostr-01.yakihonne.com
  wss://nostr-02.dorafactory.org
  wss://relay.damus.io
  wss://nostr-01.dorafactory.org
  wss://nos.lol
  wss://nostr-pub.wellorder.net
  wss://relay.snort.social

**Comment by hazeycode** [comment]
https://github.com/hoytech/strfry/blob/e4e79af1214e38ea90f4d099bd1f057a688abdb6/src/events.cpp#LL284C17-L287C23 ?

**Comment by mostafa-khaldi** [comment]
@hazeycode ?

**Comment by Darecjo** [comment]
@fiatjaf any thoughts on this?

**Comment by fiatjaf** [comment]
My thoughts are that you shouldn't use these things as `d` tags.

**Comment by mostafa-khaldi** [comment]
@fiatjaf what things? The unique values or the String in a URL format?

**Comment by fiatjaf** [comment]
The URLs. If they are not working then stop using them!

**Comment by mostafa-khaldi** [comment]
I use only unique values, but this should be declared on the specifications of the `d` tag so people should avoid them, this has caused my app to crash several time because of this error, please make this explicitly explained in the `d` tag specification.

**Comment by Pranoy1c** [comment]
‘d’ tags should be standardized to be a ‘slug’ followed by a hyphen and the ‘id’. That would make it unique and also be useful for SEO purposes to link to a specific event.

@fiatjaf thoughts?

**Comment by earonesty** [comment]
why would the relay care what value was in the "d" tag, im confused.  it's just an arbitrary string.  i typically use:  `base64(appid)-<key>` as a key value store for apps.  usually works fine.

**Comment by Darecjo** [comment]
We couldn't retrieve articles within nip-51 list that contains the "d" tag as a url, since we need the "d" tag to preserve the article after re-editing. You may check the images and the link down below for a brief demonstration, for such search the "d" tag must be generated uniquely for each event.

![Screenshot 2023-06-06 at 12 11 09 AM](https://github.com/nostr-protocol/nips/assets/29741039/3c188c37-62b5-466a-bdd7-299aa85c0eaf | width=100)
![Screenshot 2023-06-06 at 12 13 12 AM](https://github.com/nostr-protocol/nips/assets/29741039/c1c599ae-5705-409e-9472-366fee944a5d | width=100)

Event id: f98b3043018e8f6b524fc17f94ab813fe2563cc294affcd41a89d63b316495b1
Curation url that contains the article:[https://yakihonne.com/curations/naddr1qq2nwsm6gv6kvm2sw3pxgs65dfynwnn3xfxkuq3q0hkhvgxtupjdrvqjv04lsmr58th8h6tw8lp6ghdeav9qkcdthemsxpqqqp6nzq503d4](https://yakihonne.com/curations/naddr1qq2nwsm6gv6kvm2sw3pxgs65dfynwnn3xfxkuq3q0hkhvgxtupjdrvqjv04lsmr58th8h6tw8lp6ghdeav9qkcdthemsxpqqqp6nzq503d4)

**Comment by Darecjo** [comment]
You are right, it was a front end bug involving the truncation, it is solved. Thanks !
