### ISSUE TITLE
List of user relays

### ISSUE THREAD

**Issue by ondra-novak** [nostr-protocol/nips#612]
Hi.

There is a KIND-10002  to store and advertise user's relays.

However the most currently popular clients use KIND-3 and the list is stored as JSON in the content. Nobody is reading KIND-10002.

I can't find exact specification about this format. Which NIP is it?

**Comment by fiatjaf** [comment]
It's not specified because it was a hack intended to be used inside a single client and not a interoperable protocol. Clients are expected to change. You are wrong in assuming that no one is reading kind 10002, there are dozens of clients reading kind 10002. It is probably just Damus and a couple of others that aren't, but that is expected to change, they just didn't get to it yet.

If you want to read that it is just a JSON object with relay URL and a sub-object with `"read"` and `"write"` keys.
