### ISSUE TITLE
NIP-01: state exact meanings of the since/until property in filters

### ISSUE THREAD

**Issue by jiftechnify** [nostr-protocol/nips#650]
It seems that there is no consensus about whether events with `created_at` *exactly equal to* the value of `since`/`until` are considered to match the filter or not.

FYI, behaviors of major relay/protocol implementations summarized(as of 2023-07-09):
| implementation | an event matches a filter if... |
| -------------- | -------------- |
| [nostr-rs-relay](https://github.com/scsibug/nostr-rs-relay/blob/dad69118074d56d0e70873a8444ba0d88d9e2a18/src/repo/sqlite.rs#L1108-L1117)             | `since <  created_at <  until` |
| [nostream](https://github.com/Cameri/nostream/blob/f23740073f6b59b230157528376a89ca44af3f27/src/repositories/event-repository.ts#L117-L123)          | `since <= created_at <= until` |
| [strfry](https://github.com/hoytech/strfry/blob/e5ec135e78170756f5fd83a2cf4e25d611efd1ce/src/DBQuery.h#L63-L73)                                      | `since <= created_at <= until` |
| [relayer(for stored events)](https://github.com/fiatjaf/relayer/blob/55f0f5a225a016f9d14ec0738e81ee8b3dfececa/storage/postgresql/query.go#L161-L168) | `since <  created_at <  until` |
| [relayer(for real-time events, based on go-nostr)](https://github.com/nbd-wtf/go-nostr/blob/v0.18.11/filter.go#L66-L72)                              | `since <= created_at <= until` |
| [nostr-tools' `matchFilter`](https://github.com/nbd-wtf/nostr-tools/blob/a55fb8465fb2b96dcbce61ec789759bf49ad4013/filter.ts#L44-L45)                 | `since <= created_at <  until` |

I think it's due to lack of rigor in specifications about them, and we should fix it.  It's not clear that which behavior is the best, so I'd like to hear your opinions.

Personally, I would prefer the `since <= created_at <= until` behavior, considering current popularity of the interpretation and its usefulness. `since < created_at < until` might be the correctest behavior as per the English grammar but I found it's not very useful. `since <= created_at < until` is popular interpretation of time ranges in general, but I'm hesitant to support it because somehow it's not very popular in Nostr ecosystem.

**Comment by SnowCait** [comment]
`since <= created_at < until` is good for program.

**Comment by mikedilger** [comment]
3 of 6 implementations use inclusive (since <= created_at <= until).  It is also IMHO what the English interpretation is to me.  Plus, if someone didn't want events at the endpoints, so what... they get a small number of extra events and may ignore them based on the created_at value.  Going the other way would be more serious as you can't differentiate if the relay doesn't include that second, or if there were no events on that second.

So for these three reasons, I'm in favor of `since <= created_at <= until`

**Comment by AsaiToshiya** [comment]
GitHub and Twitter seem to be `since <= created_at <= until`.

**Comment by penpenpng** [comment]
Generally speaking, it is preferable to have one open and the other closed. However, it is difficult to draw a general conclusion as to which is preferable because it depends on the direction of paging in a given use case.

Fortunately or unfortunately, created_at is an integer value with rough precision, so it would not be a fatal problem if both ends were closed.

**Comment by jiftechnify** [comment]
Thank you all for your input.

To summarize your opinions, half-open intervals are generally preferable and useful but in Nostr this isn't the case and closed intervals are more natural and useful. This may be because the language of Nostr subscription filters lacks expressiveness (compared to systems like SQL etc., and I think it's nice as it keeps Nostr simple).

Based on that I decided to standardize `since <= created_at <= until`.
