### ISSUE TITLE
report events or pubkeys

### ISSUE THREAD

**Issue by fernandolguevara** [nostr-protocol/nips#66]
add a new kind of event to allow report events or pubkeys 

```json

{
    "pubkey": "<pub-key>",
    "created_at": 1000000000,
    "kind": 8, // report kind
    "tags": [
      ["p", "<pub-key-report>", "wss://..."],
      ["e", "<event-id-report>", "wss://...", "report"],
    ],
    "content": "<reason>",
    "id": "<event-id>"
}

```

**Comment by fiatjaf** [comment]
I don't know if this makes sense except in a centralized fashion where a user is reporting another user to the central judge and ruler of the platform because it is a spammer or something. In this case it wuold be reporting to whom? I think the generalized reputation scheme (I don't know where is the link to that proposal anymore) would be better than this and can serve other use cases too.

**Comment by fernandolguevara** [comment]
@fiatjaf this could help relays administrator's to take action on that reported events / public keys

**Comment by monlovesmango** [comment]
actually i think this could be really useful if we have a generalized reputation scheme maybe? someone with good reputation can publicly mark someone as a scammer for all to see.

though in general I think this event is prone to misuse, if the entities using these events are discerning it could be useful.
